# Generated by Django 3.2.12 on 2025-06-26 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='fecha',
        ),
    ]
